/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_0002fxsb_0002finterprolog_0002fNativeEngine */

#ifndef _Included_com_0002fxsb_0002finterprolog_0002fNativeEngine
#define _Included_com_0002fxsb_0002finterprolog_0002fNativeEngine
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: numberOfInstances */
/* Inaccessible static: class_00024com_00024declarativa_00024interprolog_00024PrologEngine */
/*
 * Class:     com_0002fxsb_0002finterprolog_0002fNativeEngine
 * Method:    xsb_setDebug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_com_0002fxsb_0002finterprolog_0002fNativeEngine_xsb_1setDebug
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_0002fxsb_0002finterprolog_0002fNativeEngine
 * Method:    xsb_init_internal
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_0002fxsb_0002finterprolog_0002fNativeEngine_xsb_1init_1internal
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_0002fxsb_0002finterprolog_0002fNativeEngine
 * Method:    xsb_command_string
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_0002fxsb_0002finterprolog_0002fNativeEngine_xsb_1command_1string
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_0002fxsb_0002finterprolog_0002fNativeEngine
 * Method:    xsb_close_query
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_0002fxsb_0002finterprolog_0002fNativeEngine_xsb_1close_1query
  (JNIEnv *, jobject);

/*
 * Class:     com_0002fxsb_0002finterprolog_0002fNativeEngine
 * Method:    put_bytes
 * Signature: ([BIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_0002fxsb_0002finterprolog_0002fNativeEngine_put_1bytes
  (JNIEnv *, jobject, jbyteArray, jint, jint, jstring);

/*
 * Class:     com_0002fxsb_0002finterprolog_0002fNativeEngine
 * Method:    get_bytes
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_0002fxsb_0002finterprolog_0002fNativeEngine_get_1bytes
  (JNIEnv *, jobject);

/*
 * Class:     com_0002fxsb_0002finterprolog_0002fNativeEngine
 * Method:    xsb_interrupt
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_0002fxsb_0002finterprolog_0002fNativeEngine_xsb_1interrupt
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
